import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { DatabaseSync } from "node:sqlite";

import { describe, expect, it } from "vitest";

import { InMemoryConsentStore, ReadOnlyToolGateway } from "../src/read-only-gateway.js";
import { inventoryDigest, type ToolInventory } from "../src/context-gateway.js";
import { InMemoryRunGrantRepository, RunGrantStore, type RunGrantRequest } from "../src/run-grants.js";
import { SqliteAuditSink } from "../src/sqlite-audit.js";

const NOW = "2026-08-06T12:00:00.000Z";
function database() { const directory = mkdtempSync(join(tmpdir(), "soren-audit-")); return { path: join(directory, "audit.sqlite"), cleanup: () => rmSync(directory, { recursive: true, force: true }) }; }
function appendThree(sink: SqliteAuditSink) { sink.append({ code: "A", occurredAt: NOW }); sink.append({ code: "B", occurredAt: NOW }); sink.append({ code: "C", occurredAt: NOW }); }
function gatewayFixture(sink?: SqliteAuditSink, failing = false) {
  const inventory: ToolInventory = { providerId: "provider", protocolVersions: ["2026-08-01"], tools: [{ id: "read", description: "Read", readOnly: true, exposesProjectContent: false }] };
  const request: RunGrantRequest = { runId: "run", providerId: "provider", toolIds: ["read"], inventoryDigest: inventoryDigest(inventory), protocolVersion: "2026-08-01", extensions: [], issuedAt: "2026-08-06T11:00:00.000Z", expiresAt: "2026-08-06T13:00:00.000Z", maxCalls: 2, maxResponseBytes: 64, maxTotalResponseBytes: 128 };
  const grants = new RunGrantStore({ issuerId: "issuer", repository: new InMemoryRunGrantRepository() }); const grant = grants.issue(request, inventory, NOW);
  const gateway = new ReadOnlyToolGateway({ inventory: () => inventory, call: async () => { if (failing) throw new Error("do-not-persist-provider-secret"); return { ok: true }; } }, grants, new InMemoryConsentStore([]), () => NOW, sink);
  return { gateway, grant };
}

describe("SQLite audit sink", () => {
  it("creates an empty schema-versioned audit store", () => { const value = database(); const sink = new SqliteAuditSink(value.path); try { expect(sink.schemaVersion()).toBe(1); expect(sink.readAll()).toEqual([]); } finally { sink.close(); value.cleanup(); } });
  it("persists a chained audit history across restart", () => { const value = database(); const first = new SqliteAuditSink(value.path); try { appendThree(first); } finally { first.close(); } const second = new SqliteAuditSink(value.path); try { expect(second.readAll().map((event) => event.code)).toEqual(["A", "B", "C"]); } finally { second.close(); value.cleanup(); } });
  it("serializes appends from already-open audit sink instances", () => { const value = database(); const first = new SqliteAuditSink(value.path); const second = new SqliteAuditSink(value.path); try { for (let index = 0; index < 20; index += 1) (index % 2 === 0 ? first : second).append({ code: `E${index}`, occurredAt: NOW }); const one = first.readAll(); const two = second.readAll(); expect(one).toHaveLength(20); expect(one.map((event) => event.sequence)).toEqual(Array.from({ length: 20 }, (_, index) => index + 1)); expect(two.at(-1)?.digest).toBe(one.at(-1)?.digest); } finally { first.close(); second.close(); value.cleanup(); } });
  it("continues the existing chain after repository restart", () => { const value = database(); const first = new SqliteAuditSink(value.path); let final = ""; try { final = first.append({ code: "A", occurredAt: NOW }).digest; } finally { first.close(); } const second = new SqliteAuditSink(value.path); try { expect(second.append({ code: "B", occurredAt: NOW }).previousDigest).toBe(final); } finally { second.close(); value.cleanup(); } });
  it("rejects an audit row whose code was modified without recomputing its digest", () => { const value = database(); const sink = new SqliteAuditSink(value.path); try { sink.append({ code: "A", occurredAt: NOW }); } finally { sink.close(); } const raw = new DatabaseSync(value.path); try { raw.prepare("UPDATE audit_events SET code = 'tampered' WHERE sequence = 1").run(); } finally { raw.close(); } const reopened = new SqliteAuditSink(value.path); try { expect(() => reopened.readAll()).toThrow("Invalid stored audit chain."); } finally { reopened.close(); value.cleanup(); } });
  it("rejects a forked previous digest", () => { const value = database(); const sink = new SqliteAuditSink(value.path); try { appendThree(sink); } finally { sink.close(); } const raw = new DatabaseSync(value.path); try { raw.prepare("UPDATE audit_events SET previous_digest = 'sha256:0000000000000000000000000000000000000000000000000000000000000000' WHERE sequence = 3").run(); } finally { raw.close(); } const reopened = new SqliteAuditSink(value.path); try { expect(() => reopened.readAll()).toThrow("Invalid stored audit chain."); } finally { reopened.close(); value.cleanup(); } });
  it("rejects a missing audit sequence", () => { const value = database(); const sink = new SqliteAuditSink(value.path); try { appendThree(sink); } finally { sink.close(); } const raw = new DatabaseSync(value.path); try { raw.prepare("DELETE FROM audit_events WHERE sequence = 2").run(); } finally { raw.close(); } const reopened = new SqliteAuditSink(value.path); try { expect(() => reopened.readAll()).toThrow("Invalid stored audit chain."); } finally { reopened.close(); value.cleanup(); } });
  it("rejects an invalid stored audit digest", () => { const value = database(); const sink = new SqliteAuditSink(value.path); try { sink.append({ code: "A", occurredAt: NOW }); } finally { sink.close(); } const raw = new DatabaseSync(value.path); try { raw.prepare("UPDATE audit_events SET digest = 'sha256:0000000000000000000000000000000000000000000000000000000000000000' WHERE sequence = 1").run(); } finally { raw.close(); } const reopened = new SqliteAuditSink(value.path); try { expect(() => reopened.readAll()).toThrow("Invalid stored audit chain."); } finally { reopened.close(); value.cleanup(); } });
  it("stores no provider error or request detail", () => { const value = database(); const sink = new SqliteAuditSink(value.path); try { sink.append({ code: "PROVIDER_FAILED", occurredAt: NOW }); const raw = new DatabaseSync(value.path); try { const rows = raw.prepare("SELECT * FROM audit_events").all(); const encoded = JSON.stringify(rows); for (const text of ["do-not-persist-provider-secret", "provider error", "request input", "project snapshot", "policy snapshot"]) expect(encoded).not.toContain(text); } finally { raw.close(); } } finally { sink.close(); value.cleanup(); } });
  it("persists gateway audit events across gateway and sink restart", async () => { const value = database(); const sink = new SqliteAuditSink(value.path); const first = gatewayFixture(sink); await first.gateway.call(first.grant, "read", {}, { projectSnapshot: "p", policySnapshot: "q" }); sink.close(); const reopened = new SqliteAuditSink(value.path); try { const second = gatewayFixture(reopened); expect(second.gateway.auditEvents().some((event) => event.code === "TOOL_CALLED")).toBe(true); } finally { reopened.close(); value.cleanup(); } });
  it("persists only PROVIDER_FAILED for a provider rejection", async () => { const value = database(); const sink = new SqliteAuditSink(value.path); try { const fixture = gatewayFixture(sink, true); await expect(fixture.gateway.call(fixture.grant, "read", {}, { projectSnapshot: "p", policySnapshot: "q" })).rejects.toThrow("do-not-persist-provider-secret"); expect(fixture.gateway.auditEvents().filter((event) => event.code === "PROVIDER_FAILED")).toHaveLength(1); expect(fixture.gateway.auditEvents().some((event) => event.code === "TOOL_CALLED")).toBe(false); const raw = new DatabaseSync(value.path); try { expect(JSON.stringify(raw.prepare("SELECT * FROM audit_events").all())).not.toContain("do-not-persist-provider-secret"); } finally { raw.close(); } } finally { sink.close(); value.cleanup(); } });
  it("uses an in-memory audit sink by default", async () => { const fixture = gatewayFixture(); await fixture.gateway.call(fixture.grant, "read", {}, { projectSnapshot: "p", policySnapshot: "q" }); expect(fixture.gateway.auditEvents().map((event) => event.code)).toEqual(["TOOL_CALLED"]); });
});
