export const ERROR_CODES = [
  "CAPABILITY_UNKNOWN",
  "CONNECTOR_INVALID",
  "CONNECTOR_NOT_SELECTABLE",
  "EVIDENCE_INCOMPLETE",
  "EXECUTION_FAILED",
  "LICENSE_UNRESOLVED",
  "NEEDS_USER_INPUT",
  "NO_COMPATIBLE_PROVIDER_SET",
  "OWNERSHIP_CONFLICT",
  "PLAN_DRIFT",
  "POLICY_DENIED",
  "PROJECT_NOT_DETECTED",
  "PROTOCOL_NEGOTIATION_FAILED",
  "ROLLBACK_FAILED",
  "SCHEMA_NOT_FOUND",
  "SCHEMA_VERSION_MISMATCH",
  "SOURCE_STALE",
  "SOURCE_UNAVAILABLE",
  "TOOL_PERMISSION_DENIED",
  "VALIDATION_FAILED",
  "VERIFICATION_FAILED",
  "VERSION_UNRESOLVED"
] as const;

export type SorenErrorCode = (typeof ERROR_CODES)[number];
